export const INCREMENT_REQUESTED = 'counter/INCREMENT_REQUESTED'
export const INCREMENT = 'counter/INCREMENT'
export const DECREMENT_REQUESTED = 'counter/DECREMENT_REQUESTED'
export const DECREMENT = 'counter/DECREMENT'

export const SMS_ENROLMENT_REQUESTED = 'enrolment/SMS_ENROLMENT_REQUESTED'
export const SMS_ENROLMENT_VERIFICATION_REQUESTED = 'enrolment/SMS_ENROLMENT_VERIFICATION_REQUESTED'
export const SMS_ENROLMENT_STARTED = 'enrolment/SMS_ENROLMENT_STARTED'
export const SMS_ENROLMENT_FAILED = 'enrolment/SMS_ENROLMENT_FAILED'
export const SMS_ENROLMENT_DELETING = 'enrolment/SMS_ENROLMENT_DELETING'
export const SMS_ENROLMENT_DELETED = 'enrolment/SMS_ENROLMENT_DELETED'


export const EMAIL_ENROLMENT_REQUESTED = 'enrolment/EMAIL_ENROLMENT_REQUESTED'
export const EMAIL_ENROLMENT_VERIFICATION_REQUESTED = 'enrolment/EMAIL_ENROLMENT_VERIFICATION_REQUESTED'
export const EMAIL_ENROLMENT_STARTED = 'enrolment/EMAIL_ENROLMENT_STARTED'
export const EMAIL_ENROLMENT_FAILED = 'enrolment/EMAIL_ENROLMENT_FAILED'
export const EMAIL_ENROLMENT_DELETING = 'enrolment/EMAIL_ENROLMENT_DELETING'
export const EMAIL_ENROLMENT_DELETED = 'enrolment/EMAIL_ENROLMENT_DELETED'

export const ENROLMENTS_FETCHING = 'enrolment/ENROLMENTS_FETCHING'
export const ENROLMENTS_FETCHING_ERROR = 'enrolment/ENROLMENTS_FETCHING_ERROR'
export const ENROLMENTS_FETCHED = 'enrolment/ENROLMENTS_FETCHED'

export const LOGIN = 'auth/LOGIN'
export const LOGIN_STARTED = 'auth/LOGIN_STARTED'
export const LOGIN_COMPLETED = 'auth/LOGIN_COMPLETED'
export const LOGIN_FAILED = 'auth/LOGIN_FAILED'
export const LOGOUT = 'auth/LOGOUT'

export const LOG_PASSWORD_CHANGE_ERROR = 'password/LOG_PASSWORD_CHANGE_ERROR'
export const LOG_PASSWORD_CHANGE_INFO = 'password/LOG_PASSWORD_CHANGE_INFO'
export const CLEAR_PASSWORD_CHANGE_ALERT = 'password/CLEAR_PASSWORD_CHANGE_ALERT'

export const PASSWORD_CHANGE_REQUESTED = 'password/CHANGE_REQUESTED'
export const PASSWORD_CHANGE_COMPLETED = 'password/CHANGE_COMPLETED'

export const PASSWORD_RESET_REQUESTED = 'password/RESET_REQUESTED'
export const PASSWORD_RESET_COMPLETED = 'password/RESET_COMPLETED'

export const LOG_PASSWORD_RESET_ERROR = 'password/LOG_PASSWORD_RESET_ERROR'
export const LOG_PASSWORD_RESET_INFO = 'password/LOG_PASSWORD_RESET_INFO'
export const CLEAR_PASSWORD_RESET_ALERT = 'password/CLEAR_PASSWORD_RESET_ALERT'